version: '3'

services:
  app:
    build:
      context: .
      dockerfile: myapp.Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:9000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
